version: '2'

services:
  roster-api:
    build: '.'
    command:
      - "poetry"
      - "run"
      - "uvicorn"
      - "--factory"
      - "roster_api.main:get_app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "7888"
      - "--reload"
    environment:
      - PYTHONUNBUFFERED=1
      - ROSTER_API_DEBUG=1
      - ROSTER_API_ETCD_HOST=Etcd
      - ROSTER_API_POSTGRES_HOST=Postgres
      - ROSTER_API_POSTGRES_PORT=5432
      - ROSTER_API_POSTGRES_DB=rosterdb
      - ROSTER_API_RABBITMQ_HOST=Rabbitmq
    volumes:
      - ./roster_api:/app/roster_api
    ports:
      - "7888:7888"
    depends_on:
      - Etcd
      - Postgres
  Postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=rosterdb
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
  Etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
      - "2380:2380"
  Rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672" # Management UI
      - "5672:5672"   # Default RabbitMQ port
