[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "roster-ctl"
version = "0.1.0"
description = "Roster CLI tool"
authors = ["Evan Doyle <evanmdoyle@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
openai = ">=0.27.4"
langchain = "==0.0.142"
tiktoken = "==0.3.3"
llama-index = "==0.5.22"

[tool.poetry.dev-dependencies]
black = "==23.3.0"
pytest = "==7.3.1"
twine = "==4.0.2"

[tool.poetry.scripts]
roster-ctl = "roster_ctl:main"
